### ISSUE TITLE
Update twitter and github handles

### ISSUE THREAD

**Issue by jopecko** [donaladams/donaladams.github.io#1]
Hope this finds you doing well! Noticed you changed your GH handle. You might also want to update your [config](https://github.com/donaladams/epileptic-fish.github.io/blob/master/_config.yml#L7-L8). For completeness you could also rename this repo and the link to your `sbt-parsers` repo in your [post](https://github.com/donaladams/epileptic-fish.github.io/blob/master/_posts/2016-11-20-command-line-parsing-in-sbt.md) as well, although GH handles redirects when you change your handle so up to you.

**Comment by donaladams** [comment]
Hey @jopecko thanks! I've just noticed your message from before the pandemic 😂. Hope all's well with you!
